spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URL}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          search-paths: ${SEARCH_PATH}
server:
  port: ${CONFIG_SERVER_PORT}   

management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - refresh
